# Generated by Django 2.2.12 on 2020-11-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_station', models.CharField(max_length=100)),
                ('end_station', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField(verbose_name='departure time')),
                ('arrival_time', models.DateTimeField(verbose_name='arrival time')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('departure_date', models.DateTimeField(verbose_name='departure date')),
                ('train_id', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Route')),
            ],
        ),
    ]
