# Generated by Django 2.2.12 on 2020-11-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure_time',
        ),
    ]
