# Generated by Django 2.2.12 on 2020-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201115_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='route',
            field=models.ManyToManyField(related_name='route', to='client.Route'),
        ),
    ]
