# Generated by Django 2.2.12 on 2020-11-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_ticket_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='route',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='route',
            name='ticket_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_id', to='client.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=None, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_id', to='client.TicketType'),
        ),
    ]
