# Generated by Django 3.1.2 on 2020-11-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_ticket_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='name',
            new_name='station_name',
        ),
    ]
