# Generated by Django 3.1.2 on 2020-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20201124_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
