# Generated by Django 3.1.3 on 2021-01-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20201124_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeek_days', models.PositiveSmallIntegerField(default=127)),
                ('valid_from', models.DateField(default=None, verbose_name='valid from')),
                ('valid_till', models.DateField(default=None, verbose_name='valid till')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField(default=0)),
                ('train_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='discount',
            name='ticket_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.tickettype'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_station_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='client.station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='starting_station_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='client.station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='ticket_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.tickettype'),
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(default=None, null=True, verbose_name='departure time')),
                ('arrival_time', models.TimeField(default=None, null=True, verbose_name='arrival time')),
                ('schedule_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.schedule')),
                ('station_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.station')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='train_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.train'),
        ),
        migrations.AlterField(
            model_name='route',
            name='train_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.train'),
        ),
    ]
