# Generated by Django 3.1.3 on 2021-01-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20210119_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.CharField(max_length=10),
        ),
    ]
