# Generated by Django 3.1.3 on 2021-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20210119_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='valid_untill',
        ),
        migrations.AddField(
            model_name='schedule',
            name='valid_until',
            field=models.DateField(default=None, null=True, verbose_name='valid until'),
        ),
    ]
