# Generated by Django 3.1.3 on 2021-03-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20210310_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstop',
            name='arrival_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='arrival time'),
        ),
        migrations.AlterField(
            model_name='trainstop',
            name='departure_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='departure time'),
        ),
    ]
