# Generated by Django 3.1.3 on 2021-03-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20210310_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_station_id',
            new_name='end_station',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='starting_station_id',
            new_name='starting_station',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_type_id',
            new_name='ticket_type',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
    ]
