# Generated by Django 3.1.3 on 2021-03-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20210315_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.TimeField(default=None, verbose_name='duration'),
        ),
    ]
