# Generated by Django 3.1.3 on 2021-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_route_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='arrival_date',
            field=models.TimeField(default=None, verbose_name='arrival date'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_date',
            field=models.TimeField(default=None, verbose_name='departure date'),
        ),
    ]
