# Generated by Django 3.1.3 on 2021-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20210315_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(default=None, null=True, verbose_name='departure date'),
        ),
    ]
